name: build-focal

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Set Job Parameters
        id: init
        run: |
          export CODENAME=focal
          echo ::set-output name=codename::"$CODENAME"
          echo ::set-output name=model_path::"./$CODENAME-model.json"
          echo ::set-output name=manifest_path::"./$CODENAME-manifest.txt"
          echo ::set-output name=repo_root::"./docs/ubuntu/$CODENAME"
      - uses: actions/checkout@v2
      - name: Checkout dependencies
        run: |
          git clone -b release https://github.com/regolith-linux/regolith-creche.git lib/creche/
      - name: Generate Model
        run: |
          jq -s '.[0] * .[1]' ./lib/creche/regolith-2.0.pkgmodel.json ${{ steps.vars.model_path }} > model.json
          
      - name: Generate Manifest
        run: |
          [ -e ${{ steps.vars.manifest_path }} ] && rm ${{ steps.vars.manifest_path }}
          cat model.json | ./lib/creche/build-manifest.sh ./manifest-raw.txt /tmp/manifest
          sort ./manifest-raw.txt > ${{ steps.vars.manifest_path }}
          rm ./manifest-raw.txt
          echo "Generated manifest:"
          cat ${{ steps.vars.manifest_path }}
      
      - name: Check if there are changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11
      
      - name: Configure GPG Key
        if: steps.changes.outputs.changed == 1
        run: |
          mkdir -p ~/.gnupg/
          printf "$GPG_SIGNING_KEY" | base64 --decode > ~/.gnupg/private.key
          gpg --batch --import ~/.gnupg/private.key
        env:
          GPG_SIGNING_KEY: ${{ secrets.PACKAGE_PRIVATE_KEY }}

      - name: Generate Package Repository
        if: steps.changes.outputs.changed == 1
        run: |
          export DEBEMAIL="regolith.linux@gmail.com"
          export DEBFULLNAME="Regolith Linux"
          sudo apt update
          sudo apt install -y devscripts
          sudo apt install -y reprepro
          ./lib/creche/build-deb-repo.sh ./model.json ${{ steps.vars.repo_root }} /tmp/reprepro ${{ steps.vars.codename }}
          rm ./model.json

#      - name: Test Install
#        if: steps.changes.outputs.changed == 1
#        run: |
#          echo "deb [trusted=yes] file:/tmp/reprepro ./" > /etc/apt/sources.list.d/regolith-test.list
#          apt update
#          apt install regolith-desktop-small

      - name: Commit Files
        if: steps.changes.outputs.changed == 1
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ${{ steps.vars.repo_root }}/*
          git add ${{ steps.vars.manifest_path }}
          git commit -am "Automated repo update"
          
      - name: Push Changes
        if: steps.changes.outputs.changed == 1
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
